import { pgTable, serial, text, real, integer, timestamp } from "drizzle-orm/pg-core";

export const authTokens = pgTable("auth_tokens", {
  id: serial("id").primaryKey(),
  provider: text("provider").notNull(),
  tokenType: text("token_type").notNull(),
  accessToken: text("access_token").notNull(),
  refreshToken: text("refresh_token"),
  expiresAt: text("expires_at"),
  adAccountId: text("ad_account_id"),
  pageId: text("page_id"),
  businessId: text("business_id"),
  businessName: text("business_name"),
  createdAt: timestamp("created_at").defaultNow().notNull(),
  updatedAt: timestamp("updated_at").defaultNow().notNull(),
});

export const projects = pgTable("projects", {
  id: serial("id").primaryKey(),
  name: text("name").notNull(),
  status: text("status").notNull().default("draft"),
  campaignObjective: text("campaign_objective"),
  budgetType: text("budget_type").notNull().default("CBO"),
  dailyBudget: real("daily_budget"),
  lifetimeBudget: real("lifetime_budget"),
  adAccountId: text("ad_account_id"),
  businessId: text("business_id"),
  mode: text("mode").notNull().default("create"),
  metaSourceCampaignId: text("meta_source_campaign_id"),
  driveFolderUrl: text("drive_folder_url"),
  rawDocumentText: text("raw_document_text"),
  parsedStructureJson: text("parsed_structure_json"),
  namingTemplate: text("naming_template"),
  metaCampaignId: text("meta_campaign_id"),
  destinationUrl: text("destination_url"),
  createdAt: timestamp("created_at").defaultNow().notNull(),
  updatedAt: timestamp("updated_at").defaultNow().notNull(),
});

export const adSets = pgTable("ad_sets", {
  id: serial("id").primaryKey(),
  projectId: integer("project_id").notNull().references(() => projects.id),
  name: text("name").notNull(),
  generatedName: text("generated_name"),
  targetingJson: text("targeting_json"),
  placementsJson: text("placements_json"),
  budget: real("budget"),
  bidStrategy: text("bid_strategy").notNull().default("LOWEST_COST_WITHOUT_CAP"),
  optimizationGoal: text("optimization_goal").notNull().default("OFFSITE_CONVERSIONS"),
  metaAdsetId: text("meta_adset_id"),
  status: text("status").notNull().default("pending"),
  createdAt: timestamp("created_at").defaultNow().notNull(),
});

export const ads = pgTable("ads", {
  id: serial("id").primaryKey(),
  adSetId: integer("ad_set_id").notNull().references(() => adSets.id),
  name: text("name").notNull(),
  generatedName: text("generated_name"),
  creativeRef: text("creative_ref"),
  creativeMappingJson: text("creative_mapping_json"),
  headline: text("headline"),
  primaryText: text("primary_text"),
  description: text("description"),
  cta: text("cta").notNull().default("SHOP_NOW"),
  url: text("url"),
  urlTags: text("url_tags"),
  metaAdId: text("meta_ad_id"),
  metaCreativeId: text("meta_creative_id"),
  status: text("status").notNull().default("pending"),
  createdAt: timestamp("created_at").defaultNow().notNull(),
});

export const creatives = pgTable("creatives", {
  id: serial("id").primaryKey(),
  projectId: integer("project_id").notNull().references(() => projects.id),
  originalName: text("original_name").notNull(),
  baseName: text("base_name"),
  format: text("format"),
  aspectRatio: text("aspect_ratio"),
  mediaType: text("media_type"),
  localPath: text("local_path"),
  fileSizeBytes: integer("file_size_bytes"),
  driveFileId: text("drive_file_id"),
  metaImageHash: text("meta_image_hash"),
  metaVideoId: text("meta_video_id"),
  uploadStatus: text("upload_status").notNull().default("pending"),
  selected: integer("selected").notNull().default(1),
  thumbnailPath: text("thumbnail_path"),
  adsetName: text("adset_name"),
  createdAt: timestamp("created_at").defaultNow().notNull(),
});

export const deployLog = pgTable("deploy_log", {
  id: serial("id").primaryKey(),
  projectId: integer("project_id").notNull().references(() => projects.id),
  step: text("step").notNull(),
  entityName: text("entity_name"),
  metaId: text("meta_id"),
  status: text("status").notNull().default("pending"),
  errorMessage: text("error_message"),
  createdAt: timestamp("created_at").defaultNow().notNull(),
});
